# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: Roy Quiñonez

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: ""

description:
author: 
  name: Roy Quiñonez
  email: roy.alexander.ql@gmail.com
  github: Roway007
  facebook: Roy alexander Quiñonez Lara
  instagram: royalex_2001
  pinterest: ROY ALEXANDER
  bio: Software Engineer
  email_md5: 9732824c8a041799b79d3e4b90a0a1ab

# set it as url of an imagee
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
